spring:
  config:
    activate:
      on-profile: h2
  h2:
    console:
      enabled: true
---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:mysql://localhost:3306/vehicle
    username: vehicle
    password: vehicle
    driver-class-name: com.mysql.jdbc.Driver